name: test

on:
  push:
    branches:
      - develop

jobs:
  get-dir:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_exclude_root: "true"
          dir_names_max_depth: "1"
      - name: get dir names
        run: |
          json='{"dir":[]}'
          for dir in ${{env.steps.changed-files.outputs.all_changed_files}}; do
            json=$(echo $json | jq --compact-output ".dir = .dir + [\"`echo $dir`\"]");
          done;
          echo "dir_json=$json" >> $GITHUB_ENV

  dev-deploy:
    strategy:
      matrix:
        dir: ${{env.dir_json.dir}}
    steps:
      - name: test
        run: ${{matrix.dir}}
