name: test

on:
  push:
    branches:
      - develop

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - name: comm
        run: echo "dirname=$(pwd)" >> $GITHUB_ENV

      - name: out
        run: echo "${{env.dirname}}"
