name: test

on:
  push:
    branches:
      - develop

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - name: comm
        run: echo "dirname=$(pwd | awk '{sub("/.*./", "");print $0;}')" >> $GITHUB_ENV

      - name: out
        run: echo ${{env.dirname}}
