name: test

on:
  push:
    branches:
      - develop

jobs:
  get-dir:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_exclude_root: "true"
          dir_names_max_depth: "1"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  dev-deploy:
    strategy:
      matrix:
        dirs: ${{env.steps.changed-files.outputs.all_changed_files}}
    steps:
      - name: echo
        run: echo ${{matrix.dirs}}
