name: test

on:
  push:
    branches:
      - develop

jobs:
  get_dir_names:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${steps.get_dir_names.outputs.dir_names}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_exclude_root: "true"
          dir_names_max_depth: "1"

      - name: get dir names
        id: get_dir_names
        run: |
          dir_names=()
          for dir in ${{env.steps.changed-files.outputs.all_changed_files}}; do
            dir_names+=($dir);
          done;
          echo "dir_names=${dir_names[@]}" >> "$GITHUB_OUTPUT"

  dev-deploy:
    if: ${{ needs.get_dir_names.outputs.dir_names }} != ''
    runs-on: ubuntu-latest
    needs: get_dir_names
    strategy:
      matrix:
        dir: ${{ needs.get_dir_names.outputs.dir_names }}
    steps:
      - name: test
        run: ${{ matrix.dir }}
