name: test

on:
  push:
    branches:
      - develop

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - name: comm
        run: echo "dirname=$(pwd | awk '{sub("/.*./", "");print $0;}')" >> $GITHUB_ENV

      - name: out
        run: echo ${{env.dirname}}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names_max_depth: "1"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
