name: test

on:
  push:
    branches:
      - develop

jobs:
  get_dir_names:
    runs-on: ubuntu-latest
    outputs:
      dir_names: ${{steps.get_dir_names.outputs.dir_names}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          files_ignore: ".github/**"
          dir_names_exclude_root: "true"
          dir_names_max_depth: "1"

      - name: get_dir_names
        id: get_dir_names
        run: |
          dir_names=$(printf '%s\n' ${{ steps.changed-files.outputs.all_changed_files }} | jq -R . | jq -s -c .)
          echo "dir_names=$dir_names" >> "$GITHUB_OUTPUT"

  dev-deploy:
    needs: get_dir_names
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.get_dir_names.outputs.dir_names) }}
    steps:
      - name: Checkout
        if: matrix.dir != '.github'
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: "npm"
          cache-dependency-path: ./${{ matrix.dir }}/package-lock.json

      - name: Install dependencies
        working-directory: ./${{ matrix.dir }}
        run: "npm i"

      - name: zipping
        working-directory: ./${{ matrix.dir }}
        run: "zip -r deploy.zip ."

      - name: test2
        run: ls -la ${{ matrix.dir }}
